// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exajvoaiimevizphlukl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4YWp2b2FpaW1ldml6cGhsdWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjczNjcsImV4cCI6MjA2NzQwMzM2N30.um-_tBHgkGTVoVGQI1CrNx2JCuKq3W2t3oM6xUwBZ14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});